### ISSUE TITLE
Add support for sass

### ISSUE THREAD

**Issue by Darhagonable** [CanopyTax/kremling-babel-plugin#6]
As discussed in https://github.com/CanopyTax/kremling/issues/56 having support for inline scss would be great

**Comment by geoctrl** [comment]
added support sass! #13 

see the readme for an example of setting up: 
https://github.com/CanopyTax/kremling-babel-plugin#babelrc-example

**Comment by Darhagonable** [comment]
Works great! Thanks! 😃
